"""
Device ORM Model.

Represents a monitored Windows endpoint registered by the agent.

Design decisions:
  - `device_uuid` is the persistent ID generated by DeviceIdentityManager
    on the agent side. It is the natural key used by agents for all API calls.
  - `is_online` is updated by heartbeat pings and a background task.
  - `last_seen_at` lets the dashboard show "last seen X minutes ago".
  - `owner_id` links to User — a device belongs to the user who registered it.

Relationships:
  - Belongs to one User.
  - Has many Metrics (time-series telemetry snapshots).
  - Has many Alerts.
  - Has many AIAnalysis records.
"""

from datetime import datetime
from typing import List, Optional, TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.metric import Metric
    from app.models.alert import Alert
    from app.models.ai_analysis import AIAnalysis


class Device(Base):
    __tablename__ = "devices"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Agent-generated persistent UUID (e.g. "dev_4516524eda03...")
    device_uuid: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)

    # Human-readable info populated on first registration / heartbeat
    hostname: Mapped[str] = mapped_column(String(255), nullable=False, default="unknown")
    display_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    os_name: Mapped[str] = mapped_column(String(100), nullable=False, default="Windows")
    os_version: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    architecture: Mapped[str] = mapped_column(String(50), nullable=False, default="")
    agent_version: Mapped[str] = mapped_column(String(30), nullable=False, default="0.0.0")
    mac_address: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    ip_address: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)

    # Status tracking
    is_online: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_disabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    last_seen_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    registered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # FK to User
    owner_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True
    )

    # Relationships
    owner: Mapped[Optional["User"]] = relationship("User", back_populates="devices")
    metrics: Mapped[List["Metric"]] = relationship(
        "Metric", back_populates="device", cascade="all, delete-orphan"
    )
    alerts: Mapped[List["Alert"]] = relationship(
        "Alert", back_populates="device", cascade="all, delete-orphan"
    )
    ai_analyses: Mapped[List["AIAnalysis"]] = relationship(
        "AIAnalysis", back_populates="device", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Device id={self.id} uuid={self.device_uuid!r} hostname={self.hostname!r}>"
