"""Update User model for production SaaS auth

Revision ID: 3b5db8b8085e
Revises: bf4915fc02fe
Create Date: 2026-08-03 17:15:23.449192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5db8b8085e'
down_revision: Union[str, Sequence[str], None] = 'bf4915fc02fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_disabled', sa.Boolean(), nullable=True))
        
    op.execute("UPDATE users SET password_hash = hashed_password, role = CASE WHEN is_superuser = 1 THEN 'ADMIN' ELSE 'USER' END, is_verified = 1, is_disabled = 0")
    
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('password_hash', nullable=False)
        batch_op.alter_column('role', nullable=False)
        batch_op.alter_column('is_verified', nullable=False)
        batch_op.alter_column('is_disabled', nullable=False)
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('is_superuser')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'is_disabled')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
