"""sync_models

Revision ID: bf4915fc02fe
Revises: fda464920249
Create Date: 2026-08-02 20:46:02.603748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4915fc02fe'
down_revision: Union[str, Sequence[str], None] = 'fda464920249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('mac_address', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_disabled')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'mac_address')
    op.drop_column('devices', 'display_name')
    # ### end Alembic commands ###
